name: CI

on: [ push, pull_request ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12
      
      - name: Install global dependencies 
        run: |
          sudo apt update
          sudo npm install -g yarn
     
      - name: Install dependencies
        run: yarn
      
      - name: Lint
        run: yarn run lint
